
# on the left are the names that roughly matche the USBtoUSB documentation
# first value is the byte that needs to be sent to the com port
# second value is the pygame key that would be pressed
# third value is the character that would be pressed with the shift key
keymap = {
    "`": [1, "K_BACKQUOTE", "~"],
    "1": [2, "K_1", "!"],
    "2": [3, "K_2", "@"],
    "3": [4, "K_3", "#"],
    "4": [5, "K_4", "$"],
    "5": [6, "K_5", "%"],
    "6": [7, "K_6", "^"],
    "7": [8, "K_7", "&"],
    "8": [9, "K_8", "*"],
    "9": [10, "K_9", "("],
    "0": [11, "K_0", ")"],
    "-": [12, "K_MINUS", "_"],
    "=": [13, "K_EQUALS", "+"],
    "BS": [15, "K_BACKSPACE"],
    "TAB": [16, "K_TAB"],
    "q": [17, "K_q"],
    "w": [18, "K_w"],
    "e": [19, "K_e"],
    "r": [20, "K_r"],
    "t": [21, "K_t"],
    "y": [22, "K_y"],
    "u": [23, "K_u"],
    "i": [24, "K_i"],
    "o": [25, "K_o"],
    "p": [26, "K_p"],
    "[": [27, "K_LEFTBRACKET", "{"],
    "]": [28, "K_RIGHTBRACKET", "}"],
    "\\": [29, "K_BACKSLASH", "|"],
    "CAPS": [30, "K_CAPSLOCK"],
    "a": [31, "K_a"],
    "s": [32, "K_s"],
    "d": [33, "K_d"],
    "f": [34, "K_f"],
    "g": [35, "K_g"],
    "h": [36, "K_h"],
    "j": [37, "K_j"],
    "k": [38, "K_k"],
    "l": [39, "K_l"],
    ";": [40, "K_SEMICOLON", ":"],
    "'": [41, "K_QUOTE", "\""],
    "ENTER": [43, "K_RETURN"],
    "L_SHIFT": [44, "K_LSHIFT"],
    "z": [46, "K_z"],
    "x": [47, "K_x"],
    "c": [48, "K_c"],
    "v": [49, "K_v"],
    "b": [50, "K_b"],
    "n": [51, "K_n"],
    "m": [52, "K_m"],
    ",": [53, "K_COMMA", "<"],
    ".": [54, "K_PERIOD", ">"],
    "/": [55, "K_SLASH", "?"],
    "R_SHIFT": [57, "K_RSHIFT"],
    "L_CTRL": [58, "K_RSUPER"], # I'm swapping control with the super/windows/apple key, to account for the fact I usually switch that mapping on Macos
    "L_ALT": [60, "K_LALT"],
    "SPACE": [61, "K_SPACE"],
    "R_ALT": [62, "K_RALT"],
    "R_CTRL": [64, "K_LSUPER"],
    "L_WIN": [70, "K_LCTRL"],
    "R_WIN": [71, "K_RCTRL"],
    "WIN_APL": [72, ""],
    "INSERT": [75, "K_INSERT"],
    "DELETE": [76, "K_DELETE"],
    "L_ARROW": [79, "K_LEFT"],
    "HOME": [80, "K_HOME"],
    "END": [81, "K_END"],
    "UP_ARROW": [83, "K_UP"],
    "DN_ARROW": [84, "K_DOWN"],
    "PAGE_UP": [85, "K_PAGEUP"],
    "PAGE_DN": [86, "K_PAGEDOWN"],
    "R_ARROW": [89, "K_RIGHT"],
    "NUMLOCK": [90, "K_NUMLOCKCLEAR"],
    "7_NUM": [91, "K_KP_7"],
    "4_NUM": [92, "K_KP_4"],
    "1_NUM": [93, "K_KP_1"],
    "/_NUM": [95, "K_KP_DIVIDE"],
    "8_NUM": [96, "K_KP_8"],
    "5_NUM": [97, "K_KP_5"],
    "2_NUM": [98, "K_KP_2"],
    "0_NUM": [99, "K_KP_0"],
    "*_NUM": [100, "K_KP_MULTIPLY"],
    "9_NUM": [101, "K_KP_9"],
    "6_NUM": [102, "K_KP_6"],
    "3_NUM": [103, "K_KP_3"],
    "._NUM": [104, "K_KP_PERIOD"],
    "-_NUM": [105, "K_KP_MINUS"],
    "+_NUM": [106, "K_KP_PLUS"],
    "ENTER_NUM": [108, "K_KP_ENTER"],
    "ESC": [110, "K_ESCAPE"],
    "F1": [112, "K_F1"],
    "F2": [113, "K_F2"],
    "F3": [114, "K_F3"],
    "F4": [115, "K_F4"],
    "F5": [116, "K_F5"],
    "F6": [117, "K_F6"],
    "F7": [118, "K_F7"],
    "F8": [119, "K_F8"],
    "F9": [120, "K_F9"],
    "F10": [121, "K_F10"],
    "F11": [122, "K_F11"],
    "F12": [123, "K_F12"],
    "PRT_SCR": [124, "K_PRINTSCREEN"],
    "SCRL_LK": [125, ""], # no pygame keycode
    "PAUSE": [126, ""] # no pygame keycode
}